### ISSUE TITLE
[SUGGESTION] Encrypt site with Let's Encrypt [SUGGESTION]

### ISSUE THREAD

**Issue by wiesmin138** [7coil/DiscordForOffice#13]
no more adding to trusted sites.
and... it's totally free!

**Comment by 7coil** [comment]
The site is already "encrypted", and is already using Let's Encrypt.

For VSTO solutions from the internet, `AuthenticodeRequired` is enabled, which means the software needs to be signed with a suitable code signing certificate in order to display the trust prompt.
By adding the website to trusted sites, the software can display the ClickOnce trust prompt and allow the end user to run the software.
